services:
  - type: web
    name: noteplus-taller-api
    runtime: docker
    dockerfilePath: NotePlusTaller.API/Dockerfile
    dockerContext: GA8-220501096-AA1-EV01
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: SUPABASE_CONNECTION_STRING
        sync: false

  - type: web
    name: noteplus-taller-web
    runtime: docker
    dockerfilePath: NotePlusTaller.Web/Dockerfile
    dockerContext: GA8-220501096-AA1-EV01
    plan: free
